[package]
name = "mine_sweeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curses = "0.1.0"
ncurses = "5.101.0"
rand = "0.8.5"
regex = "1.9.1"
